### ISSUE TITLE
机构评级永远是买入或增持？

### ISSUE THREAD

**Issue by qhd1996** [uname-yang/pysnowball#10]
爬取了大约5000条股票的评级，没有减持，一直是增持、买入、中性

**Comment by uname-yang** [comment]
咱们碰上大牛市了。。。。数据上没有进行改动，都是雪球的，有问题可以再雪球上翻一个减持的，做个验证。

**Comment by qhd1996** [comment]
连爬三天了，沪深所有股票，都是中性或者增持
