### ISSUE TITLE
token获取方面

### ISSUE THREAD

**Issue by yzhzy12321** [uname-yang/pysnowball#25]
new user
在测试过程中发现验证cookie发生变化，服务器不再是对xq_a_token进行验证，而是对xqat验证
如果依旧使用xq_a_token，将会导致大部分功能无法使用
ps：可能就是看到了这个项目才把这个字符串缩了一下。。。

**Comment by uname-yang** [comment]
> 

有哪些功能啊？ 知道的写几个，不行我给加上

**Comment by uname-yang** [comment]
> new user 在测试过程中发现验证cookie发生变化，服务器不再是对xq_a_token进行验证，而是对xqat验证 如果依旧使用xq_a_token，将会导致大部分功能无法使用 ps：可能就是看到了这个项目才把这个字符串缩了一下。。。

调用API前需要手动获取雪球网站的token,使用set_token设置token后才能访问雪球的API。s(xq_a_token & u)
现在全部api可用
