### ISSUE TITLE
获取实时分笔数据已失效

### ISSUE THREAD

**Issue by shineyik** [uname-yang/pysnowball#7]
# 获取实时分笔数据，实时取得股票当前报价和成交信息已失效
ball.pankou(symbol)

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-6-26a780b922fc> in <module>
      1 # 获取实时分笔数据，实时取得股票当前报价和成交信息
----> 2 ball.pankou(symbol)

/opt/conda/lib/python3.8/site-packages/pysnowball/realtime.py in pankou(symbol)
     13 def pankou(symbol):
     14     url = api_ref.realtime_pankou+symbol
---> 15     return utls.fetch_without_token(url)
     16 

/opt/conda/lib/python3.8/site-packages/pysnowball/utls.py in fetch_without_token(url)
     43 
     44     if response.status_code != 200:
---> 45         raise Exception(response.content)
     46 
     47     return json.loads(response.content)

Exception: b'{"error_description":"\xe9\x81\x87\xe5\x88\xb0\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x8c\xe8\xaf\xb7\xe5\x88\xb7\xe6\x96\xb0\xe9\xa1\xb5\xe9\x9d\xa2\xe6\x88\x96\xe8\x80\x85\xe9\x87\x8d\xe6\x96\xb0\xe7\x99\xbb\xe5\xbd\x95\xe5\xb8\x90\xe5\x8f\xb7\xe5\x90\x8e\xe5\x86\x8d\xe8\xaf\x95","error_uri":"/stock/pankou.json","error_code":"400016"}'

**Comment by uname-yang** [comment]
请试下新版本吧，0.0.6 ，pankou api 要加token了，直接用不行了

**Comment by uname-yang** [comment]
以后有bug 可以加微信，我拉个群，有事及时看，这边看的不及时
